server:
  port: 9000

config:
  security:
    oauth:
      jwt:
        key: testequalquerqueprecisaterumasenhagrande

spring:
  application:
    name: psi-auth
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.uuid}}
